pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Clone Repo') {
            steps {
                sh 'git clone https://github.com/alanfinan/simple-java-maven-app.git'
            }
        }

        stage('Build') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'simple-java-maven-app/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                dir('simple-java-maven-app') {
                    sh '''
                        echo "Finding built JAR..."
                        JAR_FILE=$(ls target/*.jar | head -n 1)
                        echo "Running: $JAR_FILE"
                        java -jar "$JAR_FILE"
                    '''
                }
            }
        }

        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
