pipeline {
    agent any
    tools {
        maven 'Maven3' 
    }
    stages {

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                   sh '''
                    echo "Finding built JAR..."
                    JAR_FILE=$(ls target/*.jar | head -n 1)
                    echo "Running: $JAR_FILE"
                    java -jar "$JAR_FILE"
                '''
            }
        }

        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
